presentation/store.Web/Models/ErrorViewModel.cs
namespace store.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

presentation/store.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Store;
using Store.Memory;

namespace store.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;

        public BookController(IBookRepository bookRepository) 
        {
            this.bookRepository = bookRepository;
        }
        public IActionResult Index(int id)
        {
            Book book = bookRepository.GetById(id);
            return View(book);
        }
    }
}

presentation/store.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using store.Web.Models;

namespace store.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

presentation/store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Store;

namespace store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly BookService bookService;

        public SearchController(BookService bookService)
        {
            this.bookService = bookService;
        }

        public IActionResult Index(string query)
        {
            var books = bookService.GetAllByQuery(query);

            return View("index", books);
        }
    }
}

presentation/store.Web/Views/Book/Index.cshtml
@model Book

@{
    ViewData["Title"] = Model.Title;
}

<h1>@Model.Title</h1>
<p><strong>@Model.Author</strong></p>
<p>@Model.Description</p>
<p>Цена <strong>@Model.Price</strong></p>

presentation/store.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

presentation/store.Web/Views/Search/Index.cshtml
@model Book[]

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if (Model.Length == 0) 
{
    <p>Ничего не найдено</p>
}
else
{
    <ul>
        @foreach (var book in Model)
        {
            <li>
                <a href="@Url.Action("Index", "Book", new {id = book.Id})">@book.Title</a>
            </li>
        }
    </ul>
} 

presentation/store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Интеренет магазин на С#</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/store.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Интернет магазин на С#</a>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("Index", "Search")"method="get">
                <input class="form-control mr-sm-0" type= "search" name="query" placeholder="Автор или название "/>
                <button class="bth bth-outline-success my-2 my-sm-2" type="submit">Искать</button>
            </form>
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>